name: Hori Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # database-relational-block
      # - name: Run e2e tests for Hori Backend with TypeORM
      #   id: relational
      #   run: docker compose -f docker-compose.relational.ci.yaml --env-file env-example-relational -p ci-relational up --build --exit-code-from api

      # - name: Copy prod.log from container to host
      #   if: ${{ failure() && steps.relational.conclusion == 'failure' }}
      #   run: docker cp ci-relational-api-1:/usr/src/app/prod.log .

      # database-document-block
      # - name: Run e2e tests for Hori Backend with Mongoose
      #   id: document
      #   run: docker compose -f docker-compose.document.ci.yaml --env-file env-example-document -p ci-document up --build --exit-code-from api

      # - name: Copy prod.log from container to host
      #   if: ${{ failure() && steps.document.conclusion == 'failure' }}
      #   run: docker cp ci-document-api-1:/usr/src/app/prod.log .

      # - name: Upload prod.log to artifacts for debugging
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: prod-logs
      #     path: prod.log

      # Build and push Docker image to Docker Hub
      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get current date and build number
        id: vars
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/hori-backend:${{ env.DATE }}-${{ env.BUILD_NUMBER }} .

      - name: Push Docker image to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hori-backend:${{ env.DATE }}-${{ env.BUILD_NUMBER }}
